[package]
name = "point"
version = "0.1.0"
authors = ["lanocci <16540010+lanocci@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
num-traits = "0.2.14"
