[workspace]
members = [
  "devide_and_concur_search",
  "koch_curve",
  "fibonacci",
  "lcs",
  "matrix_chain_multiplication",
  "coin_changing_problem",
  "knapsac_problem",
  "longest_increasing_subsequence",
  "largest_square",
]