[workspace]
members = [
  "bubble_sort",
  "insertion_sort",
  "selection_sort",
  "judge_stable",
  "merge_sort",
  "partition",
  "quick_sort",
  "counting_sort",
  "topological_sort",
  "shell_sort",
  "number_of_inversions",
  "minimum_cost_sort",
]