[workspace]
members = [
  "stack",
  "queue",
  "doubly_linked_list",
  "rooted_tree",
  "binary_tree",
  "tree_walk",
  "binary_search_tree",
  "complete_binary_tree",
  "complete_binary_tree_printing",
  "maximum_heap",
]